apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-mysql
  description: Go packages for MySQL
  annotations:
    business-unit: EverHealth
    github.com/project-slug: updox/go-mysql
    product: UPD
spec:
  type: service
  lifecycle: production
  owner: EverHealth
  implementation:
    languages:
    - Go
    - Shell
    - Makefile
